### ISSUE TITLE
Severe issue

### ISSUE THREAD

**Issue by EddieTheEd** [spicata/mint-garden#1]
You keep on copying me

I starred the highlight thing first and then you did. 

This is very suspicious.

**Comment by spicata** [comment]
You literally copied the idea for a website (after an endless amount of banter from me).

**Comment by EddieTheEd** [comment]
On cap no god you godding

**Comment by EddieTheEd** [comment]
(i am not anti-religion btw)

**Comment by spicata** [comment]
ok, but counter argument
![image](https://user-images.githubusercontent.com/99490352/185006896-334da432-1325-4c84-98dc-aab25819615c.png)
